// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXSeW9alk6k8jFf18LqzBrBxqbjrOmn34',
    appId: '1:178437734569:web:53e9b742121ed86aeee9b8',
    messagingSenderId: '178437734569',
    projectId: 'evolt-sys',
    authDomain: 'evolt-sys.firebaseapp.com',
    storageBucket: 'evolt-sys.firebasestorage.app',
    measurementId: 'G-RDGH9S7L1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmcOO3DgdOj4OE-eHO1gFPErtbAIMjTkk',
    appId: '1:178437734569:android:9b2605fddecdd102eee9b8',
    messagingSenderId: '178437734569',
    projectId: 'evolt-sys',
    storageBucket: 'evolt-sys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBI1acOjbn980nwlZJl-iM2MN8T-wvvY8',
    appId: '1:178437734569:ios:4f013f85bcc10207eee9b8',
    messagingSenderId: '178437734569',
    projectId: 'evolt-sys',
    storageBucket: 'evolt-sys.firebasestorage.app',
    iosBundleId: 'com.example.evoltsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBI1acOjbn980nwlZJl-iM2MN8T-wvvY8',
    appId: '1:178437734569:ios:4f013f85bcc10207eee9b8',
    messagingSenderId: '178437734569',
    projectId: 'evolt-sys',
    storageBucket: 'evolt-sys.firebasestorage.app',
    iosBundleId: 'com.example.evoltsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXSeW9alk6k8jFf18LqzBrBxqbjrOmn34',
    appId: '1:178437734569:web:f428f56e58393a98eee9b8',
    messagingSenderId: '178437734569',
    projectId: 'evolt-sys',
    authDomain: 'evolt-sys.firebaseapp.com',
    storageBucket: 'evolt-sys.firebasestorage.app',
    measurementId: 'G-TDK896HVSF',
  );
}
